# Generated by Django 5.0.7 on 2024-08-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar_serie_pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_o_pelicula', models.CharField(choices=[('Serie', 'Serie'), ('Pelicula', 'Película')], max_length=120, verbose_name='Serie/Pelicula')),
                ('titulo_serie', models.CharField(max_length=120, verbose_name='Titulo')),
                ('fecha_serie', models.IntegerField(verbose_name='Año')),
                ('temporadas', models.IntegerField(blank=True, null=True, verbose_name='Nº Temporadas')),
                ('episodios', models.IntegerField(blank=True, null=True, verbose_name='Nº Episodios')),
                ('plataforma', models.CharField(max_length=120, verbose_name='Plataforma')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('genero', models.CharField(choices=[('Drama', 'Drama'), ('Comedia', 'Comedia'), ('Ciencia ficción', 'Ciencia ficción'), ('Fantasía', 'Fantasía'), ('Acción', 'Acción'), ('Terror', 'Terror'), ('Aventura', 'Aventura'), ('Thriller', 'Thriller'), ('Policial', 'Policial'), ('Histórica', 'Histórica'), ('Animación', 'Animación'), ('Romance', 'Romance'), ('Documental', 'Documental'), ('Musical', 'Musical'), ('Western', 'Western'), ('Guerra', 'Guerra'), ('Biográfica', 'Biográfica'), ('Cine negro', 'Cine negro'), ('Cine experimental:', 'Cine experimental:'), ('Cine de arte', 'Cine de arte')], max_length=120, verbose_name='Género')),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Puntuacion (Del 1 al 10)')),
                ('finalizada', models.BooleanField(default=False, verbose_name='Finalizada?')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('serie_pelicula_imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('recomendado_por', models.CharField(max_length=120, verbose_name='Recomendado Por')),
            ],
        ),
    ]
